---
title: '2019-04-24'
author: "???遠"
date: "4/24/2019"
output: html_document
---
```{r}
m2<-matrix(c("a","b","c","d"),2,2)
m2
class(m2)
typeof(m2)
a<-m2[[1]]
c<-m2[[3]]
bd<-m2[2,]
a
c
bd
```
```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
MAT2[c(1,4)]
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF$姓名)
```
```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
class(StuList)
```
```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```
```{r}
StuDF4
```

```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
chosenletters <- letters[1:16]
matObj1 <- matrix(chosenletters,4,4)
matObj1
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```

```{r}
matObj1
matObj1[c(T,F,F,T,F),c(F,T,T)]
matObj1[c(1,4),c(2,3)] #取第一和第四列，第二和第三行
matObj1[c(1,4),c(F,T,T)] #可以數字和Logical混搭
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
classSurvey[c(1:60),c(F,F,F,T,T,F)]
classSurvey[,c(4,5)]
classSurvey[c("性別","本學期學分數")]
```

