---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
studentMajors0 <- 
  c("經濟系", "經濟系", "法律系")

```
```{r}
class(studentMajors)
```

```{r}
class(studentMajors0)
```
```{r}
typeof(studentMajors)
```

```{r}
levels(studentMajors)
```
```{r}
as.integer(studentMajors)
```

```{r}
birthplace<- factor(
  c("台北市","台中市","台北市","台北市","台中市")
)
```
```{r}
as.integer(birthplace)
```
```{r}
typeof(birthplace)
```
```{r}
class(birthplace)
```
```{r}
levels(birthplace)
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```
```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```
```{r}
class(dtObject)
```

```{r}
dtObjectVector
```
```{r}
as.integer(dtObject)
```

```{r}
as.double(dtObjectVector)
```
```{r}
Sys.timezone()
```

