---
title: '2019-05-15'
author: "林茂廷"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["??迂4"]]
```

## colnames/ rownames

```{r}
StuDF2 <- data.frame(
  摮貉??=c(172,214,322,425,517),
  憪??=c("撠??","憭折??","????","撠","憭抒"),
  ??蜀=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[[2]] <- c("憪??")
colnames(StuDF2)
StuDF2

```
 
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2

```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b
b[[3]]<-FALSE
b[[5]]<-7
b
```
```{r}
library(readr)
library(lubridate)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
exData3[[1]]<- ymd(exData3[[1]])
class(exData3[[1]])
```
```{r}
isAsiaCrisis<- exData3[[1]]>= ymd("1997-06-01") & exData3[[1]]<=ymd("1998-12-01") #要把日期轉換為ymd
isAsiaCrisis
```

```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
target<-transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[target, ]
```
```{r}
utility_cobb_douglass <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```
```{r}
new <- function(x,.alpha){newvalue<-x+.alpha
        return(newvalue)}
new(1,.alpha=3)
```
```{r}
S<- function(a,b,P){Qs<- a+b*P
      return(Qs)}
S(0,1,P=1)
D<- function(c,d,P){Qd<- c-d*P
      return(Qd)}
D(5,1,1)
```
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
gpa_fun("105S60ba1")
```
```{r}
library(readr)
library(lubridate)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"

(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$UTC時間[nyLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York"),tzone="UTC")
invoiceList$UTC時間[tpLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei"),tzone="UTC")

invoiceList 
```
```{r}
ymd_hms("1973-02-21 12:05:22",tzone="America/New_York")-> fromDateTIme
with_tz(fromDateTIme, tzone="Asia/Taipei")-> toDateTime

ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tzone=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```
```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```
```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911  #?<=(民國)：取出前面的字是"民國"的數字[:digit:]+們
mm<-str_extract(twDates,"[:digit:]+(?=月)")  #取出後面接著月的數字
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```
```{r}
date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
```

```{r}
date_convert_twYM <- function(twDates,dd="01"){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  return(yyyymmdd)
}
date_convert_twYM("民國85年4月30日", "30")
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass(y=2, x=1,.beta=0.8,05)
```
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for(i in seq_along(gmailAddress)){
  print(gmailAddress[[i]])
}
```

```{r}
library(stringr)
for(i in seq_along(gmailAddress)){
  if (str_detect(gmailAddress[[i]],"@gmail.com")){
    print(gmailAddress[[i]])}
  else{
    print(str_c(gmailAddress[[i]],"@gmail.com"))
  }

}
```

```{r}
# 開始設定
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```
```{r}
i<-1
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]][["commit"]][["author"]][["name"]])
}

```

```{r}
i<-1
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]][["commit"]][["committer"]][["name"]])
}
```

```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]][["commit"]][["committer"]][["date"]])
}
```



```{r}

for(i in seq_along(commitHistory)){
  print(
    str_c(
      "Author is ",
      commitHistory[[i]][["commit"]][["author"]][["name"]],
      ". Committer is ",
      commitHistory[[i]][["commit"]][["committer"]][["name"]]
      )
    )
}
```

```{r}
for(i in seq_along(commitHistory)){
  if((commitHistory[[i]][["commit"]][["author"]][["name"]])==(commitHistory[[i]][["commit"]][["committer"]][["name"]]))
  print(commitHistory[[i]][["commit"]][["author"]][["name"]])
}

```

```{r}
for(i in seq_along(commitHistory)){
  (commitHistory[[i]][["commit"]][["author"]][["name"]]==
     commitHistory[[i]][["commit"]][["committer"]][["name"]]) ->
    logiResult
  print(logiResult)  
}
```


##0.saving container
```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory))
```
##1.sequence source
```{r}
commitHistory
```
##2.body 存下來「第i個」commit的author
```{r}
i<- 1

commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
```
##check
```{r}
saveCommitAuthor
```
##3.for loop
```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
}

saveCommitAuthor
```


